version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
naturalist = true
farmersdelight = true
cratedelight = true
culturaldelights = true
create = true
storagedelight = true
connectedglass = true
interiors = true
another_furniture = true
friendsandfoes = true
minecraft = true
animal_feeding_trough = true
comforts = true
create_enchantment_industry = true
beautify = true
railways = true
bellsandwhistles = true
milk = true
sliceanddice = true
createframed = true
villagersplus = true
extendedgears = true
vegandelight = true
expandeddelight = true
creategoggles = true
