# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				frog = true
				hoglin = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				goat = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				evoker = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				eye_of_ender = true
				villager = true
				wolf = true
				fishing_bobber = true
				zombie_villager = true
				strider = true
				polar_bear = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				canary = true
				firefly = true
				bluejay = true
				snake = true
				coral_snake = true
				cardinal = true
				catfish = true
				boar = true
				robin = true
				dragonfly = true
				bass = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				finch = true

			[light_sources.settings.entities.immersive_aircraft]
				biplane = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.create]
				carriage_contraption = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				ice_chunk = true
				moobloom = true
				iceologer = true
				crab = true
				rascal = true

